// <auto-generated />

#nullable disable

using CSharpBlog.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace CSharpBlog.Repository.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20220808202413_addSeedingBlogUserData")]
    partial class addSeedingBlogUserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSharpBlog.Repository.Model.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blog", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd6c9dc8-97af-4ad5-a361-a79e9b2b60da"),
                            Content = "C# Blog",
                            Created = new DateTime(2022, 8, 8, 20, 24, 13, 840, DateTimeKind.Utc).AddTicks(9230),
                            LastModified = new DateTime(2022, 8, 8, 20, 24, 13, 840, DateTimeKind.Utc).AddTicks(9230),
                            Title = "C# Blog",
                            UserId = new Guid("354fa244-3c83-438b-9f2b-284707fd3936")
                        },
                        new
                        {
                            Id = new Guid("fd6c9dc8-97af-4ad5-a361-a79e9b2b60db"),
                            Content = "C# Blog 2",
                            Created = new DateTime(2022, 8, 8, 20, 24, 13, 840, DateTimeKind.Utc).AddTicks(9230),
                            LastModified = new DateTime(2022, 8, 8, 20, 24, 13, 840, DateTimeKind.Utc).AddTicks(9230),
                            Title = "C# Blog 2",
                            UserId = new Guid("354fa244-3c83-438b-9f2b-284707fd3935")
                        });
                });

            modelBuilder.Entity("CSharpBlog.Repository.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("354fa244-3c83-438b-9f2b-284707fd3935"),
                            Email = "asd@gmail.com",
                            Name = "User",
                            Password = "123456",
                            Username = "user"
                        },
                        new
                        {
                            Id = new Guid("354fa244-3c83-438b-9f2b-284707fd3936"),
                            Email = "asdf@gmail.com",
                            Name = "User1",
                            Password = "123456",
                            Username = "user1"
                        });
                });

            modelBuilder.Entity("CSharpBlog.Repository.Model.Blog", b =>
                {
                    b.HasOne("CSharpBlog.Repository.Model.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSharpBlog.Repository.Model.User", b =>
                {
                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
